#+Title: Installing and setting up ELK server 
#+Date: November 7, 2016
#+Author: VLEAD Systems 

* Introduction 
  This document mentions the requirements, prerequisites, installation
  steps and custom configuration used to set up ELK (Elasticsearch
  Logstash Kibana server).


* Why ELK ?
  + ELK is a combined solution given by elastic.co to store logs in
    certain formats and then a visualization tool takes care of
    visualization of obtained logs in the form of nice graphs. A user
    can interact with ELK server using web based HTTP(S) API to write,
    read, update, delete data into elasticsearch NOSQL database.
  + There was no specific reason to choose NOSQL database, still VLABS
    analaytics being in the form of document results choosing
    elasticsearch as a good choice.
  + The Kibana visualization tool needs minimal intervention to
    produce graphs from the records/data stored in elasticsearch
    database.
  + As a result of this, ELK provides a complete package to satisfy
    the requirements with minimal efforts.

  

+ [[../requirements/index.org][Requirements]]

+ [[../design/index.org][Design]]

+ [[../deployment/index.org][Deployment]]

* Post Deployment
   + Login to VM
   + Configure nginx  ::
      #+BEGIN_SRC command
       cp /root/labs/elk-stack-for-analytics/scripts/elasticsearch-nginx.conf /etc/nginx/sites-enabled/default    
      #+END_SRC
   + Create dashboard admin user  ::
      Create a user named vlabs-dashboard and give some password to it.
      #+BEGIN_SRC command
       sudo htpasswd -c /etc/nginx/htpasswd.users <dashboard-username>
       sudo htpasswd -c /etc/nginx/htpasswd.users vlabs-dashboard
      #+END_SRC

   + Restart services
       #+BEGIN_SRC command
       service nginx restart 
       service elasticsearch restart
       service kibana restart
       service logstash restart
       #+END_SRC
  
  

* References
  + [[https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-ubuntu-14-04][Install ELK]]
  + [[https://www.elastic.co/][Learn ELK]]
  + [[http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html][Install Java 8]]
  
